In [15]:
import numpy as np
x=np.arange(-10,10,1)
y1=2*x+3+np.random.randn(len(x))
y2=2*x*x+3+np.random.randn(len(x))
y = x + np.random.normal(-10, 10, 1)

In [12]:
np.corrcoef(x,y1)

array([[1.        , 0.99511238],
       [0.99511238, 1.        ]])

In [13]:
np.corrcoef(x,y2)

array([[ 1.        , -0.19117078],
       [-0.19117078,  1.        ]])

In [14]:
x

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [16]:
y

array([-8.64473964, -7.64473964, -6.64473964, -5.64473964, -4.64473964,
       -3.64473964, -2.64473964, -1.64473964, -0.64473964,  0.35526036,
        1.35526036,  2.35526036,  3.35526036,  4.35526036,  5.35526036,
        6.35526036,  7.35526036,  8.35526036,  9.35526036, 10.35526036])

In [17]:
np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])